### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by shepardac** [covertcodes/gammarf#17]
Hello I have completed the Docker build . command ..however I seem to be stuck there. I have the Image ID BUT where do I insert it in the rungrf.sh file?

**Comment by covertcodes** [comment]
A few things to note.  The ./prepare command will build everything, the ./run.sh command will run it.  You don't need to update it by hand anymore.  The docs are inaccurate now - it's just finishing up a major rehaul.  They'll be updated in a couple of weeks, if everything goes smooth.  Because it's in the rehaul, it's best to come back to it later when the changes are thoroughly tested.  Can I ask about your use case?

**Comment by shepardac** [comment]
Thank you for your reply, I will be looking forward for the update. Im sorry, I do not understand to what a use case refers to.

**Comment by gammarf** [comment]
A release is now at https://github.com/gammarf/gammarf; the docs are updated at http://gammarf.io/index.html.  You may need to refresh to see the new docs.  Please let me know if you have any questions (email is best), or if the docs are confusing.
